package com.live.rrutt.hurricane;

import com.live.rrutt.hurricane.scala.PokerTable;
import com.live.rrutt.ui.*;

import java.io.*;

public class HurricanePoker 
		extends javax.swing.JFrame 
		implements Serializable {

	private static final long serialVersionUID = 2785996048582414206L;
	
	public static final int windowHeight = 240;

	private javax.swing.JScrollPane outputScrollPane;

	private javax.swing.JTextArea outputArea;

	public HurricanePoker(String[] args) {		
		initComponents();
		pack();
		
		setBounds(
			TextWindow.windowX, 
			TextWindow.windowY + TextWindow.windowHeight, 
			TextWindow.windowWidth, 
			windowHeight);

		setVisible(true);
		
		PokerTable.PlayPoker(this);
		exitForm(null);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the FormEditor.
	 */
	protected void initComponents() {
		outputScrollPane = new javax.swing.JScrollPane();
		outputArea = new javax.swing.JTextArea();
		getContentPane().setLayout(new java.awt.GridBagLayout());
		java.awt.GridBagConstraints gridBagConstraints1;
		setTitle("Welcome to the Poker Table");

		outputScrollPane.setPreferredSize(new java.awt.Dimension(150, 200));
		outputScrollPane.setFont(new java.awt.Font("Courier New", 0, 12));
		outputScrollPane.setAutoscrolls(true);

		outputArea.setColumns(1);
		outputArea.setRows(1);
		outputArea.setFont(new java.awt.Font("Courier New", 0, 12));
		outputScrollPane.setViewportView(outputArea);

		gridBagConstraints1 = new java.awt.GridBagConstraints();
		gridBagConstraints1.gridx = 0;
		gridBagConstraints1.gridy = 0;
		gridBagConstraints1.fill = java.awt.GridBagConstraints.BOTH;
		gridBagConstraints1.weightx = 100.0;
		gridBagConstraints1.weighty = 95.0;
		getContentPane().add(outputScrollPane, gridBagConstraints1);

		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				exitForm(evt);
			}
		});
	}

	protected void exitForm(java.awt.event.WindowEvent evt) {
		this.setVisible(false);
		this.dispose();
		try {
			// Assume we are running as an application.
			System.exit(0);
		} catch (Exception ex) {
			outputArea.append("\n\nApplet finished.\n\nRefresh browser to restart\nor close browser page to exit.\n");
			// Probably running as an applet, so do nothing.
		}
	}
	
	public void write(String s) {
		outputArea.append(s);
		outputArea.setCaretPosition(outputArea.getText().length());
	}

	public static void main(String args[]) {
		new HurricanePoker(args).setVisible(true);
	}
}
